apps/polls/urls.py
from django.urls import path
from .views import PollsDashboardView, PollCreateView, PollListView, PollDetailView, AlreadyVotedView

app_name = "polls"

urlpatterns = [
    path('home/', PollsDashboardView.as_view(), name = "home"),
    path('create/', PollCreateView.as_view(), name='poll_create'),
    path('list/', PollListView.as_view(), name='poll_list'),
    path('poll/<int:pk>/', PollDetailView.as_view(), name='poll_detail'),
    path('already_voted/', AlreadyVotedView.as_view(), name='already_voted'),
]

apps/user/urls.py
from django.urls import path
from .views import LoginView, SignupView, UserLogoutView

from django.views.generic import TemplateView

app_name = "user"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("signup/", SignupView.as_view(), name="signup"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from .views import LoginRedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LoginRedirectView.as_view(), name = 'index'),
    path('user/', include('apps.user.urls')),
    path('polls/', include('apps.polls.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

apps/templates/includes/breadcrumb.html
{% load replace_value %}

<div class="page-header">
  <div class="page-block">
    <div class="row align-items-center">
      <div class="col-md-12">
        <div class="page-header-title">
          <h5 class="m-b-10">{{ segment|replace_value:"_" }}</h5>
        </div>
        <ul class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'index' %}"><i class="feather icon-home"></i></a></li>
          {% if parent %}
            <li class="breadcrumb-item"><a href="javascript:">{{ parent|replace_value:"_" }}</a></li>
          {% endif %}
          <li class="breadcrumb-item"><a href="javascript:">{{ segment|replace_value:"_" }}</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

apps/templates/includes/head.html
{% load static %}

<title>Quick Polling</title>
<!-- HTML5 Shim and Respond.js IE11 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 11]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
<!-- Meta -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<meta name="description"
      content="Free Datta Able Admin Template come up with latest Bootstrap 4 framework with basic components, form elements and lots of pre-made layout options"/>
<meta name="keywords"
      content="admin templates, bootstrap admin templates, bootstrap 4, dashboard, dashboard templets, sass admin templets, html admin templates, responsive, bootstrap admin templates free download,premium bootstrap admin templates, datta able, datta able bootstrap admin template, free admin theme, free dashboard template"/>
<meta name="author" content="CodedThemes"/>

<!-- Favicon icon -->
<link rel="icon" href="{% static 'assets/images/favicon.ico' %}" type="image/x-icon">
<!-- fontawesome icon -->
<link rel="stylesheet" href="{% static 'assets/fonts/fontawesome/css/fontawesome-all.min.css' %}">
<!-- animation css -->
<link rel="stylesheet" href="{% static 'assets/plugins/animation/css/animate.min.css' %}">
<!-- vendor css -->
<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
<!-- dark mode css -->
<link rel="stylesheet" href="{% static 'assets/css/dark.css' %}">

apps/templates/includes/navigation.html
{% load static %}

<header class="navbar pcoded-header navbar-expand-lg navbar-light">
  <div class="m-header">
    <a class="mobile-menu" id="mobile-collapse1" href="javascript:"><span></span></a>
    <a href="{% url 'index' %}" class="b-brand">
      <div class="b-bg">
        <i class="feather icon-trending-up"></i>
      </div>
      <span class="b-title">Datta Able</span>
    </a>
  </div>
  <a class="mobile-menu" id="mobile-header" href="javascript:">
    <i class="feather icon-more-horizontal"></i>
  </a>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <li><a href="javascript:" class="full-screen" onclick="javascript:toggleFullScreen()"><i
            class="feather icon-maximize"></i></a></li>
      <li class="nav-item dropdown">
        <a class="dropdown-toggle" href="javascript:" data-toggle="dropdown">Dropdown</a>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="javascript:">Action</a></li>
          <li><a class="dropdown-item" href="javascript:">Another action</a></li>
          <li><a class="dropdown-item" href="javascript:">Something else here</a></li>
        </ul>
      </li>
      <li class="nav-item">
        <div class="main-search">
          <div class="input-group">
            <input type="text" id="m-search" class="form-control" placeholder="Search . . .">
            <a href="javascript:" class="input-group-append search-close">
              <i class="feather icon-x input-group-text"></i>
            </a>
            <span class="input-group-append search-btn btn btn-primary">
              <i class="feather icon-search input-group-text"></i>
            </span>
          </div>
        </div>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li>
        <label>
          <i class="icon feather icon-sun" id="theme-indicator"></i>
          <input type="checkbox" id="theme-switch" class="d-none">
        </label>
      </li>
      <li>
        <div class="dropdown">
          <a class="dropdown-toggle" href="javascript:" data-toggle="dropdown"><i
              class="icon feather icon-bell"></i></a>
          <div class="dropdown-menu dropdown-menu-right notification">
            <div class="noti-head">
              <h6 class="d-inline-block m-b-0">Notifications</h6>
              <div class="float-right">
                <a href="javascript:" class="m-r-10">mark as read</a>
                <a href="javascript:">clear all</a>
              </div>
            </div>
            <ul class="noti-body">
              <li class="n-title">
                <p class="m-b-0">NEW</p>
              </li>
              <li class="notification">
                <div class="media">
                  <img class="img-radius" src="{% static 'assets/images/user/avatar-1.jpg' %}" alt="Generic placeholder image">
                  <div class="media-body">
                    <p><strong>John Doe</strong><span class="n-time text-muted"><i
                          class="icon feather icon-clock m-r-10"></i>30 min</span></p>
                    <p>New ticket Added</p>
                  </div>
                </div>
              </li>
              <li class="n-title">
                <p class="m-b-0">EARLIER</p>
              </li>
              <li class="notification">
                <div class="media">
                  <img class="img-radius" src="{% static 'assets/images/user/avatar-2.jpg' %}" alt="Generic placeholder image">
                  <div class="media-body">
                    <p><strong>Joseph William</strong><span class="n-time text-muted"><i
                          class="icon feather icon-clock m-r-10"></i>30 min</span></p>
                    <p>Prchace New Theme and make payment</p>
                  </div>
                </div>
              </li>
              <li class="notification">
                <div class="media">
                  <img class="img-radius" src="{% static 'assets/images/user/avatar-3.jpg' %}" alt="Generic placeholder image">
                  <div class="media-body">
                    <p><strong>Sara Soudein</strong><span class="n-time text-muted"><i
                          class="icon feather icon-clock m-r-10"></i>30 min</span></p>
                    <p>currently login</p>
                  </div>
                </div>
              </li>
            </ul>
            <div class="noti-footer">
              <a href="javascript:">show all</a>
            </div>
          </div>
        </div>
      </li>
      <li>
        <div class="dropdown drp-user">
          <a href="javascript:" class="dropdown-toggle" data-toggle="dropdown">
            <i class="icon feather icon-settings"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right profile-notification">
            <div class="pro-head">
              <img src="{% static 'assets/images/user/avatar-1.jpg' %}" class="img-radius" alt="User-Profile-Image">
              <span>John Doe</span>
              {% if request.user.is_authenticated %}
                {% if request.user.is_superuser %}
                <a href="{% url 'admin:logout' %}" class="dud-logout" title="Logout">
                {% else %}
                <a href="{% url 'user:logout' %}" class="dud-logout" title="Logout">
                {% endif %}
                  <i class="feather icon-log-out"></i>
                </a>
              {% endif %}
            </div>
            <ul class="pro-body">
              <li><a href="#" class="dropdown-item"><i class="feather icon-settings"></i>
                  Settings</a></li>
              <li><a href="#" class="dropdown-item"><i class="feather icon-user"></i>
                  Profile</a></li>
              <li><a href="#" class="dropdown-item"><i class="feather icon-mail"></i> My
                  Messages</a></li>
              <li><a href="{% url 'user:logout' %}" class="dropdown-item"><i class="feather icon-lock"></i> Logout
                  </a></li>
              {% if request.user.is_authenticated %}
              <li>
                {% if request.user.is_superuser %}
                <a href="{% url 'admin:password_change' %}" class="dropdown-item">
                {% else %}
                <a href="#" class="dropdown-item">
                {% endif %}
                  <i class="feather icon-edit"></i>Change Password
                </a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </li>
    </ul>
  </div>
</header>

apps/templates/includes/pre-loader.html
<!-- [ Pre-loader ] start -->
<div class="loader-bg">
  <div class="loader-track">
    <div class="loader-fill"></div>
  </div>
</div>
<!-- [ Pre-loader ] End -->

apps/templates/includes/scripts.html
{% load static %}

<!-- Required Js -->
<script src="{% static 'assets/js/vendor-all.min.js' %}"></script>
<script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/pcoded.min.js' %}"></script>
<script src="{% static 'assets/js/dark-mode.js' %}"></script>

apps/templates/includes/sidebar.html
{% load static %}

<nav class="pcoded-navbar">
  <div class="navbar-wrapper">
    <div class="navbar-brand header-logo">
      <a href="{% url 'index' %}" class="b-brand">
        <div class="b-bg">
          <i class="feather icon-trending-up"></i>
        </div>
        <span class="b-title">Quick Polling</span>
      </a>
      <a class="mobile-menu" id="mobile-collapse" href="javascript:"><span></span></a>
    </div>
    <div class="navbar-content scroll-div">
      <ul class="nav pcoded-inner-navbar">
        <li class="nav-item pcoded-menu-caption">
          <label>Navigation</label>
        </li>
        <li data-username="dashboard Default Ecommerce CRM Analytics Crypto Project" class="nav-item {% if 'index' in segment %}active{% endif %}">
          {% if request.user.is_superuser %}
          <a href="{% url 'polls:home' %}" class="nav-link ">
          {% else %}
          <a href="{% url 'index' %}" class="nav-link ">
          {% endif %}
            <span class="pcoded-micon"><i class="feather icon-home"></i></span><span class="pcoded-mtext">Dashboard</span>
          </a>
        </li>
        <li class="nav-item {% if 'tables' in segment %}active{% endif %}">
          <a href="{%url 'polls:poll_list' %}" class="nav-link "><span class="pcoded-micon"><i
                class="feather icon-server text-c-green"></i></span><span class="pcoded-mtext">Polls</span></a>
        </li>
        <li class="nav-item">
          <a href = "{% url 'polls:poll_create' %}" class="nav-link "><span class="pcoded-micon"><i
                class="feather icon-zap text-c-green"></i></span><span class="pcoded-mtext">Create Poll</span></a>
        </li>       
      </ul>
    </div>
  </div>
</nav>