apps/user/urls.py
from django.urls import path
from .views import LoginView, SignupView, UserLogoutView

from django.views.generic import TemplateView

app_name = "user"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("signup/", SignupView.as_view(), name="signup"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from .views import LoginRedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LoginRedirectView.as_view(), name = 'index'),
    path('user/', include('apps.user.urls')),
    path('polls/', include('apps.polls.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

apps/templates/accounts/auth-change-password.html
{% extends 'layouts/base-auth.html' %}
{% load static %}

{% block content %}

    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <form method="post" class="card-body text-center">
                    {% csrf_token %}

                    <div class="mb-4">
                        <i class="feather icon-user-plus auth-icon"></i>
                    </div>
                    <h3 class="mb-4">Reset Password</h3>
                    {% for field in form %}
                    <div class="input-group mb-3">
                        {{ field }}
                    </div>
                    <span class="text-danger d-block text-left">{{ field.errors }}</span>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary shadow-2 mb-4">Sign up</button>
                    <p class="mb-0 text-muted">Go to <a href="{% url 'index' %}"> Dashboard </a></p>
                </form>
            </div>
        </div>
    </div>


    <label class="d-none">
        <i class="icon feather icon-sun" id="theme-indicator"></i>
        <input type="checkbox" id="theme-switch" class="d-none">
    </label>

{% endblock content %}

apps/templates/accounts/auth-password-change-done.html
{% extends 'layouts/base-auth.html' %}
{% load static %}

{% block content %}

<div class="auth-wrapper">
  <div class="auth-content">
    <div class="auth-bg">
      <span class="r"></span>
      <span class="r s"></span>
      <span class="r s"></span>
      <span class="r"></span>
    </div>
    <div class="card">
      <form class="card-body text-center">

        <div class="mb-4">
          <i class="feather icon-unlock auth-icon"></i>
        </div>
        <h3 class="mb-4">Password Changed Done</h3>

        <div class="input-group mb-3">
          Your password has been changed successfully.
        </div> 
        <p class="mb-0 text-muted">Go to <a href="{% url 'index' %}">dashboard</a></p>
      </form>
    </div>
  </div>
</div>

<label class="d-none">
  <i class="icon feather icon-sun" id="theme-indicator"></i>
  <input type="checkbox" id="theme-switch" class="d-none">
</label>

{% endblock content %}

apps/templates/accounts/auth-password-reset-complete.html
{% extends 'layouts/base-auth.html' %}
{% load static %}

{% block content %}

<div class="auth-wrapper">
  <div class="auth-content">
    <div class="auth-bg">
      <span class="r"></span>
      <span class="r s"></span>
      <span class="r s"></span>
      <span class="r"></span>
    </div>
    <div class="card">
      <form class="card-body text-center">

        <div class="mb-4">
          <i class="feather icon-unlock auth-icon"></i>
        </div>
        <h3 class="mb-4">Password Reset Complete</h3>

        <div class="input-group mb-3">
          Your password has been reset successfully. You can now login with the new password.
        </div> 
        <p class="mb-0 text-muted"><a href="{% url 'login' %}">Login</a></p>
      </form>
    </div>
  </div>
</div>

<label class="d-none">
  <i class="icon feather icon-sun" id="theme-indicator"></i>
  <input type="checkbox" id="theme-switch" class="d-none">
</label>

{% endblock content %}

apps/templates/accounts/auth-password-reset-confirm.html
{% extends 'layouts/base-auth.html' %}
{% load static %}

{% block content %}

    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <form method="post" class="card-body text-center">
                    {% csrf_token %}

                    <div class="mb-4">
                        <i class="feather icon-user-plus auth-icon"></i>
                    </div>
                    <h3 class="mb-4">Reset Password</h3>
                    {% for field in form %}
                    <div class="input-group mb-3">
                        {{ field }}
                    </div>
                    <span class="text-danger d-block text-left">{{ field.errors }}</span>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary shadow-2 mb-4">Sign up</button>
                    <p class="mb-0 text-muted">Already have an account? <a href="{% url 'login' %}"> Log in</a></p>
                </form>
            </div>
        </div>
    </div>


    <label class="d-none">
        <i class="icon feather icon-sun" id="theme-indicator"></i>
        <input type="checkbox" id="theme-switch" class="d-none">
    </label>

{% endblock content %}

apps/templates/accounts/auth-password-reset-done.html
{% extends 'layouts/base-auth.html' %}
{% load static %}

{% block content %}

<div class="auth-wrapper">
  <div class="auth-content">
    <div class="auth-bg">
      <span class="r"></span>
      <span class="r s"></span>
      <span class="r s"></span>
      <span class="r"></span>
    </div>
    <div class="card">
      <form class="card-body text-center">

        <div class="mb-4">
          <i class="feather icon-unlock auth-icon"></i>
        </div>
        <h3 class="mb-4">Password Reset Done</h3>

        <div class="input-group mb-3">
          An email has been sent to your email address. Please click the link and reset your password.
        </div> 
        <p class="mb-0 text-muted">Don’t have an account? <a href="{% url 'register' %}">Signup</a></p>
      </form>
    </div>
  </div>
</div>

<label class="d-none">
  <i class="icon feather icon-sun" id="theme-indicator"></i>
  <input type="checkbox" id="theme-switch" class="d-none">
</label>

{% endblock content %}

apps/templates/accounts/auth-reset-password.html
{% extends 'layouts/base-auth.html' %}
{% load static %}

{% block content %}

    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <form method="post" class="card-body text-center">
                    {% csrf_token %}

                    <div class="mb-4">
                        <i class="feather icon-user-plus auth-icon"></i>
                    </div>
                    <h3 class="mb-4">Reset Password</h3>
                    {% for field in form %}
                    <div class="input-group mb-3">
                        {{ field }}
                    </div>
                    <span class="text-danger d-block text-left">{{ field.errors }}</span>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary shadow-2 mb-4">Sign up</button>
                    <p class="mb-0 text-muted">Already have an account? <a href="{% url 'login' %}"> Log in</a></p>
                </form>
            </div>
        </div>
    </div>


    <label class="d-none">
        <i class="icon feather icon-sun" id="theme-indicator"></i>
        <input type="checkbox" id="theme-switch" class="d-none">
    </label>

{% endblock content %}

apps/templates/accounts/auth-signin.html
{% extends 'layouts/base-auth.html' %}
{% load static %}

{% block content %}

    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <form method="post" class="card-body text-center">
                    {% csrf_token %}

                    

                    <div class="mb-4">
                        <i class="feather icon-unlock auth-icon"></i>
                    </div>
                    <h3 class="mb-4">Login</h3>
                    {% if form.non_field_errors %}
                        {% for error in form.non_field_errors %}
                            <span class="text-danger d-block my-3">{{ error }}</span>
                        {% endfor %}
                    {% endif %}
                    {% for field in form %}
                    <div class="input-group mb-3">
                        {{ field }}
                    </div>
                    {% endfor %}
                    <div class="form-group text-left mt-4">
                        <div class="checkbox checkbox-fill d-inline">
                            <input type="checkbox" name="checkbox-fill-1" id="checkbox-fill-a1" checked="">
                            <label for="checkbox-fill-a1" class="cr"> Save Details</label>
                        </div>
                    </div>
                    <button class="btn btn-primary shadow-2 mb-4">Login</button>
                    <p class="mb-2 text-muted">Forgot password? <a href="#">Reset</a></p>
                    <p class="mb-0 text-muted">Don’t have an account? <a href="{% url 'user:signup' %}">Signup</a></p>
                </form>
            </div>
        </div>
    </div>

    <label class="d-none">
        <i class="icon feather icon-sun" id="theme-indicator"></i>
        <input type="checkbox" id="theme-switch" class="d-none">
    </label>

{% endblock content %}

apps/templates/accounts/auth-signup.html
{% extends 'layouts/base-auth.html' %}
{% load static %}

{% block content %}

    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <form method="post" class="card-body text-center">
                    {% csrf_token %}

                    <div class="mb-4">
                        <i class="feather icon-user-plus auth-icon"></i>
                    </div>
                    <h3 class="mb-4">Sign up</h3>
                    {% for field in form %}
                    <div class="input-group mb-3">
                        {{ field }}
                    </div>
                    <span class="text-danger d-block text-left">{{ field.errors }}</span>
                    {% endfor %}
                    <div class="form-group text-left mt-4">
                        <div class="checkbox checkbox-fill d-inline">
                            <input type="checkbox" name="checkbox-fill-1" id="checkbox-fill-1" checked="">
                            <label for="checkbox-fill-1" class="cr"> Save Details</label>
                        </div>
                    </div>
                    <div class="form-group text-left">
                        <div class="checkbox checkbox-fill d-inline">
                            <input type="checkbox" name="checkbox-fill-2" id="checkbox-fill-2">
                            <label for="checkbox-fill-2" class="cr">Send me the <a href="#!"> Newsletter</a> weekly.</label>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary shadow-2 mb-4">Sign up</button>
                    <p class="mb-0 text-muted">Already have an account? <a href="{% url 'user:login' %}"> Log in</a></p>
                </form>
            </div>
        </div>
    </div>


    <label class="d-none">
        <i class="icon feather icon-sun" id="theme-indicator"></i>
        <input type="checkbox" id="theme-switch" class="d-none">
    </label>

{% endblock content %}